#!/bin/bash

# Debo One-Line Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/Kevin-Kurka/Debo/main/install-oneliner.sh | bash

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Detect OS
OS="$(uname -s)"
ARCH="$(uname -m)"

echo -e "${BLUE}🤖 Debo Installer${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Check prerequisites
check_command() {
    if ! command -v $1 &> /dev/null; then
        echo -e "${RED}❌ $1 is not installed${NC}"
        return 1
    else
        echo -e "${GREEN}✅ $1 found${NC}"
        return 0
    fi
}

echo -e "\n${YELLOW}Checking prerequisites...${NC}"

# Check Node.js
if ! check_command node; then
    echo -e "${YELLOW}Installing Node.js...${NC}"
    if [[ "$OS" == "Darwin" ]]; then
        if check_command brew; then
            brew install node
        else
            echo -e "${RED}Please install Homebrew first: https://brew.sh${NC}"
            exit 1
        fi
    elif [[ "$OS" == "Linux" ]]; then
        curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
        sudo apt-get install -y nodejs
    fi
fi

# Check Git
if ! check_command git; then
    echo -e "${RED}Please install Git first${NC}"
    exit 1
fi

# Install Redis
if ! check_command redis-cli; then
    echo -e "${YELLOW}Installing Redis...${NC}"
    if [[ "$OS" == "Darwin" ]]; then
        brew install redis
        brew services start redis
    elif [[ "$OS" == "Linux" ]]; then
        sudo apt update
        sudo apt install -y redis-server
        sudo systemctl start redis
    fi
fi

# Install Ollama
if ! check_command ollama; then
    echo -e "${YELLOW}Installing Ollama...${NC}"
    curl -fsSL https://ollama.ai/install.sh | sh
fi

# Clone and setup Debo
echo -e "\n${YELLOW}Installing Debo...${NC}"

# Create installation directory
INSTALL_DIR="$HOME/.debo"
if [ -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}Removing existing installation...${NC}"
    rm -rf "$INSTALL_DIR"
fi

# Clone repository
git clone https://github.com/Kevin-Kurka/Debo.git "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Install dependencies
echo -e "${YELLOW}Installing dependencies...${NC}"
npm install --silent

# Create .env file
cat > .env << EOF
# Auto-generated by Debo installer
REDIS_URL=redis://localhost:6379
LLM_PROVIDER=ollama
OLLAMA_BASE_URL=http://localhost:11434
WEBSOCKET_PORT=3001
NODE_ENV=production
LOG_LEVEL=info
EOF

# Pull Ollama models
echo -e "\n${YELLOW}Downloading AI models (this may take a while)...${NC}"
ollama pull llama2:13b
ollama pull codellama:7b
ollama pull mistral:7b

# Create global command
echo -e "\n${YELLOW}Setting up global command...${NC}"
sudo npm link

# Run setup
echo -e "\n${YELLOW}Running initial setup...${NC}"
npm run setup

# Create directories
mkdir -p "$HOME/debo-projects"

echo -e "\n${GREEN}✨ Debo installation complete!${NC}"
echo -e "\n${BLUE}Quick Start:${NC}"
echo "  debo create my-app \"Build a todo app with React\""
echo "  debo monitor my-app"
echo "  debo deploy my-app production"
echo -e "\n${BLUE}Web Monitor:${NC} http://localhost:3001"
echo -e "${BLUE}Documentation:${NC} https://github.com/Kevin-Kurka/Debo"